# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
City.create([
{:name => 'Colombo'},
{:name => 'Dehiwala'},
{:name => 'Mount Lavinia'},
{:name => 'Moratuwa'},
{:name => 'Sri Jayawardenapura Kotte'},
{:name => 'Negombo'},
{:name => 'Kandy'},
{:name => 'Kalmunai'},
{:name => 'Vavuniya'},
{:name => 'Galle'},
{:name => 'Trincomalee'},
{:name => 'Batticaloa'},
{:name => 'Jaffna'},
{:name => 'Katunayake'},
{:name => 'Dambulla'},
{:name => 'Kolonnawa'},
{:name => 'Anuradhapura'},
{:name => 'Ratnapura'},
{:name => 'Badulla'},
{:name => 'Matara'},
{:name => 'Puttalam'},
{:name => 'Chavakacheri'},
{:name => 'Kattankudy'},
{:name => 'Matale'},
{:name => 'Kalutara'},
{:name => 'Mannar'},
{:name => 'Panadura'},
{:name => 'Beruwala'},
{:name => 'Ja-Ela'},
{:name => 'Point Pedro'},
{:name => 'Kelaniya'},
{:name => 'Peliyagoda'},
{:name => 'Kurunegala'},
{:name => 'Wattala'},
{:name => 'Gampola'},
{:name => 'Nuwara Eliya'},
{:name => 'Valvettithurai'},
{:name => 'Chilaw'},
{:name => 'Eravur'},
{:name => 'Avissawella'},
{:name => 'Weligama'},
{:name => 'Ambalangoda'},
{:name => 'Ampara'},
{:name => 'Kegalle'},
{:name => 'Hatton'},
{:name => 'Nawalapitiya'},
{:name => 'Balangoda'},
{:name => 'Hambantota'},
{:name => 'Tangalle'},
{:name => 'Moneragala'},
{:name => 'Gampaha'},
{:name => 'Horana'},
{:name => 'Wattegama'},
{:name => 'Minuwangoda'},
{:name => 'Bandarawela'},
{:name => 'Kuliyapitiya'},
{:name => 'Haputale'},
{:name => 'Talawakele'},
{:name => 'Harispattuwa'},
{:name => 'Kadugannawa'},
{:name => 'Embilipitiya'},
{:name => 'Sigiriya'}
])

100.times do 
Job.create([{:title => "Engineer", :tags => "Singh Baluchistan", :companyemail => "Usama", :city_id => 2},
	{:title => "Engineer", :tags => "Singh Baluchistan", :companyemail => "Usama", :city_id => 2},
	{:title => "Pharmacist", :tags => "Singh Khyber", :companyemail => "Huwa", :city_id => 4},
	{:title => "Worker", :tags => "Punjab", :companyemail => "Newlook", :city_id => 5},
	{:title => "Designer", :tags => "web photoshop", :companyemail => "Usama", :city_id => 3},
	{:title => "Engineer", :tags => "Singh Baluchistan", :companyemail => "adobe", :city_id => 4},
	{:title => "Styler", :tags => "colombo", :companyemail => "ntobe", :city_id => 5},
	{:title => "phonegap", :tags => "mardan", :companyemail => "adobe", :city_id => 6},
	{:title => "Dreamweaver designer", :tags => "karachi", :companyemail => "microsoft", :city_id => 7},
	{:title => "Engineer", :tags => "Singh Baluchistan", :companyemail => "Achara", :city_id => 8},
	{:title => "Engineer", :tags => "Singh Baluchistan", :companyemail => "Pakistan", :city_id => 9},
	{:title => "Engineer", :tags => "Singh", :companyemail => "Hyderabad", :city_id => 11},
	{:title => "Engineer", :tags => "Baluchistan", :companyemail => "Usama", :city_id => 9},
	{:title => "Engineer", :tags => "Peshawar", :companyemail => "Usama", :city_id => 14},
	{:title => "Engineer", :tags => "Sarhad", :companyemail => "Usama", :city_id => 10},
	{:title => "Engineer", :tags => "Singh Baluchistan", :companyemail => "Usama", :city_id => 9},
	{:title => "Engineer", :tags => "Singh Baluchistan", :companyemail => "Usama", :city_id => 3},
	{:title => "Engineer", :tags => "Singh Baluchistan", :companyemail => "Usama", :city_id => 4},
	{:title => "Engineer", :tags => "Singh Baluchistan", :companyemail => "Usama", :city_id => 4},
	{:title => "Engineer", :tags => "Singh Baluchistan", :companyemail => "Usama", :city_id => 7},
	{:title => "Engineer", :tags => "Singh Baluchistan", :companyemail => "Usama", :city_id => 7},
	{:title => "Engineer", :tags => "Singh Baluchistan", :companyemail => "Usama", :city_id => 8},
	{:title => "Engineer", :tags => "Singh Baluchistan", :companyemail => "Usama", :city_id => 10},
	{:title => "Engineer", :tags => "Singh Baluchistan", :companyemail => "Usama", :city_id => 11},
	{:title => "Engineer", :tags => "Singh Baluchistan", :companyemail => "Usama", :city_id => 17}
	])
end